### ISSUE TITLE
Missing Tootip class

### ISSUE THREAD

**Issue by WheelerMan** [Fuhrmann/xenforo-prefix-forum-listing#7]
The markup for the Show all choice is missing the XF tooltip class. So it shows as a standard ugly white tooltip below while the others show above and are matched tot the forum style. Simple fix. I posted the fix over at XF. https://xenforo.com/community/threads/prefix-forum-listing.26811/page-13

**Comment by Xon** [comment]
Resolved in v1.2.5

**Comment by WheelerMan** [comment]
Very cool. Thanks for helping Furhman out with this. BTW I'm CodeMonkey on XF forums.
